Adding cryomagnetics CS4 field source
Ecpy/ecpy_hqc_legacy pull request #6
Opened 2016-12-02 10:39 UTC by lcontami

2016-12-02 10:53 UTC, MatthieuDartiailh requested changes

2016-12-02 10:53 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/manifest.enaml
> +                    manufacturer = 'Crymagnetics'
Cryomagnetics

2016-12-02 10:53 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/manifest.enaml
> +                        model  = 'IPS120-10'
CS4 it is is not the oxford source

2016-12-02 10:53 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/manifest.enaml
> +                                       'VisaUSB': {'resource_class': 'INSTR'}
Does the CS4 support USB ?

2016-12-02 11:17 UTC, lcontami commented
Remarque:
ajouter aussi la source cryomagnetics G4 avec comme modèle 4G-100,
connexions GPIB, USB et TCPIP (à priori socket, port 4444 à vérifier);

le driver est exactement le même que celui de CS4 à la variable près FIELD_CURRENT_RATIO = 0.043965 pour G4 (voir avec Madar comment faire :) )

2016-12-02 12:57 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/instruments/drivers/visa/cryomagnetics_cs4.py
> +        """
Why this change ? this is not numpy style

2016-12-02 12:57 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/instruments/drivers/visa/cryomagnetics_cs4.py
> +        Current activity of the power supply (idle, ramping).
Same

2016-12-02 12:57 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/instruments/drivers/visa/cryomagnetics_cs4.py
> +        Field that the source will try to reach.
same

2016-12-02 12:57 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/instruments/drivers/visa/cryomagnetics_cs4.py
> +        """
same

2016-12-02 12:57 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/instruments/drivers/visa/cryomagnetics_cs4.py
> +        Rate at which to ramp the field.
same

2016-12-02 12:57 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/instruments/drivers/visa/cryomagnetics_cs4.py
> +        Ramp up the field to the specified value.
same

2016-12-02 15:13 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/instruments/drivers/visa/cryomagnetics_cs4.py
> +        """Setup the correct unit and range.
Actually there should be a blank line after the dosctring.

2016-12-05 10:48 UTC, MatthieuDartiailh submitted a review, later dismissed

2016-12-05 10:48 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/instruments/drivers/visa/cryomagnetics_cs4.py
> +        self.field_current_ratio = connection_info['magnet_conversion']
This will first raise a KeyError. Better to check the presence of the key in the dictionary

2016-12-05 10:48 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/manifest.enaml
> +                                   'ecpy_hqc_legacy.Legacy.CS4']
You could add the cg4 too

2016-12-05 10:53 UTC, lcontami commented on ecpy_hqc_legacy/instruments/drivers/visa/cryomagnetics_cs4.py
> +        self.field_current_ratio = connection_info['magnet_conversion']
Ok, indeed I was confused by the fact that there was a default value in the setting declaration... so what is the default value for ? Just display ?

2016-12-05 10:57 UTC, lcontami commented on ecpy_hqc_legacy/manifest.enaml
> +                                   'ecpy_hqc_legacy.Legacy.CS4']
They share the same driver (CS4); I did add 4G as a separate Driver extension in the manifest

2016-12-05 11:04 UTC, lcontami commented on ecpy_hqc_legacy/instruments/drivers/visa/cryomagnetics_cs4.py
> +        self.field_current_ratio = connection_info['magnet_conversion']
Ok got it. I just have to keep in mind that the code is not just for instantiation, but also need to work when the instrument has already be created... :)

2016-12-05 11:12 UTC, MatthieuDartiailh commented on ecpy_hqc_legacy/manifest.enaml
> +                                   'ecpy_hqc_legacy.Legacy.CS4']
My bad ...

2016-12-05 11:42 UTC, MatthieuDartiailh commented
Travis is unhappy. Can you try to give it a look.

2016-12-05 14:46 UTC, MatthieuDartiailh reviewed
Have you tested this on your setup ? Is it ready to be merged ?

2016-12-05 16:16 UTC, lcontami commented
I'm not very clear on how to do that. 
I started ecpy with python __main__.py (from the repertory I cloned from github, not from the conda package). I can add instruments profile (so it is linked to ecpy_hqc_legacy although I don't see how) but I don't see my drivers :( (and I don't have any error message).

... 

What am I doing wrong ?

2016-12-05 16:28 UTC, MatthieuDartiailh commented
You are editing ecpy_hqc_legacy so starting ecpy even from the clone won't help. The easiest way it is to create a conda env. (I assume the cmd line is in ecpy_hqc_legacy directory)
```
conda create -n test3 python=3 ecpy ecpy_hqc_legacy -c ecpy
activate test3
conda remove ecpy_hqc_legacy
python setup.py develop
```
For pytest you need pytest-capturelog that is available only on pip and you need to run as admin most likely.

2016-12-05 17:39 UTC, lcontami commented
Ok. Here are my issues:

- I have a warning about two drivers (extensions) sharing the same Driver (class) CS4; I can dismiss it
 
- The new setting windows (MagnetConversionSetting popup) opens behind the instrument profile edition window.
I tried to see how the windows ordering was implemented in the connections for example, but I didn't see any difference between BaseConnection and BaseSettings (and neither any specifics in VisaConnections and co).

Related remark:
the instrument edition window will not yield to ANYTHING (not the terminal, not another application...).
It might be a bit dangerous no ? (in my case, the settings popup was opening behind and there was no way to move it since I couldn't change the front window); don't know if this is very clear.

2016-12-05 19:24 UTC, MatthieuDartiailh commented
For the driver issue create a blank subclass. My point is that I do not believe two drivers can be fully identical.
For the window it is probably it is created without the proper parent. You can probably fix it in ecpy easily.

2016-12-19 14:03 UTC, lcontami commented
I took into account all of your comments.
Not sure whether this is buggy or not, I need the settings of ecpy to work correcly first.
Wating on pull request https://github.com/Ecpy/ecpy/pull/74

2016-12-19 14:40 UTC, lcontami commented
Testing it:
at the end of the profile edition (when clicking ok on the profile edition window) the program freezes and python suggest me to "consider a restart"

The instrument profile is correctly created as far as I can see:

cs.instr.ini file:

``` html
  id = cs
  model_id = Cryomagnetics.4G-100
  [connections]
      [[VisaUSB]]
          model_code = ""
          resource_class = INSTR
          interface_type = USB
          board = 0
          serial_number = ""
          manufacturer_id = ""
          usb_interface_number = 0
  [settings]
      [[conv]]
          magnet_conversion = 0.01
```

2016-12-23 10:08 UTC, lcontami commented
This is ready to merge

2016-12-23 10:20 UTC, MatthieuDartiailh commented
Waiting for https://github.com/Ecpy/ecpy/pull/74 to be merged (Travis failure is a random one so I will probably merge later today).

2017-01-11 17:15 UTC, MatthieuDartiailh approved these changes

2017-01-11 17:16 UTC, merged