Remove all uses of ask_for_values
Ecpy/ecpy_hqc_legacy pull request #71
Opened 2020-08-13 09:49 UTC by rassouly

`ask_for_values` has been deprecated by the pyvisa library so this patch updates all uses of `ask` to `query`.

TODO:
  - Testing

2020-08-13 11:51 UTC, rassouly commented
I've tested this patch for most of the instruments I have access to (with the exceptions of the AWG since the current drivers are not on master), and it seems to work

2020-08-13 13:09 UTC, MatthieuDartiailh commented
@rassouly can you list which driver you did not test ? @galactikvoyager could somebody on your side check the remaining drivers ? I am not comfortable merging without some sanity check on your side first.

2020-08-13 13:23 UTC, rassouly commented
I did not test any multimeter (Agilent or Keysight), the Cryomagnetics and Oxford current sources, the R&S VNA and ZVA and the SR lock-in. 
Some of the drivers in the folder seem to not be registered in the manifest such as the LeCroy oscilloscope (we have one but we use it manually), the agilent PSA (we've just bought one, the driver looks a bit weird but I could try it).
As I said previously, I didn't bother testing the AWGs since the drivers on this branch are quite outdated.

2020-08-13 14:14 UTC, MatthieuDartiailh commented
Thanks @rassouly, I guess @leghtas should have a look then for the R&S instruments.

2020-10-15 16:00 UTC, rassouly commented
The new version of Pyvisa has already dropped support for `ask_for_values`and nobody in Paris has commented in 2 months. Currently a new installation of exopy is not functional because of this change.
Can you merge this now? If Paris has issues, they can fix it later.

2020-10-17 01:14 UTC, MatthieuDartiailh requested changes
I suggested two minor changes I will merge once you address them.

2020-10-17 01:14 UTC, MatthieuDartiailh commented on exopy_hqc_legacy/instruments/drivers/visa_tools.py
>      def ask_for_values(self, message, format=2):
This should simply be removed since it will crash.

2020-10-17 01:14 UTC, MatthieuDartiailh commented on exopy_hqc_legacy/instruments/drivers/visa_tools.py
>      def ask(self, message):
I suggest also getting rid of this.

2020-10-17 07:34 UTC, rassouly commented
The build error is simply a timeout from the conda website when travis was trying to install exopy from conda.

2020-10-17 12:50 UTC, MatthieuDartiailh approved these changes

2020-10-19 02:50 UTC, merged

2020-10-19 02:51 UTC, MatthieuDartiailh commented
BTW can you add a releasenote about this change as part of #72 ?